name: Publish

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Code-Coverage"]
    types:
      - completed
jobs:
  Test:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    # strategy:
    #   matrix:
    #     node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker container
        run: | 
        docker build . -t ghcr.io/$GITHUB_ACTOR/linkin:latest -t ghcr.io/$GITHUB_ACTOR/linkin:${echo $GITHUB_SHA | head -c7}

      - name: Login to docker
        run:  echo $GITHUB_TOKEN | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Login to docker
        run:  docker push ghcr.io/$GITHUB_ACTOR/linkin:latest
          
      # - name: Cache node modules
      #   uses: actions/cache@v2
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
