name: Publish
# Only trigger, when the build workflow succeeded
on:
  [push, pull_request]
  # workflow_run:
  #   workflows: ["Code-Coverage"]
  #   types:
  #     - completed
jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build docker container
        run: docker build . -t ghcr.io/$GITHUB_ACTOR/linkin:latest -t ghcr.io/$GITHUB_ACTOR/linkin:$(echo $GITHUB_SHA | head -c7)

      - name: Login to docker
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{github.actor}} --password-stdin

      - name: Login to docker
        run: docker push ghcr.io/$GITHUB_ACTOR/linkin:latest
# docker build . -t ghcr.io/aa/linkin:latest -t ghcr.io/aa/linkin:${echo $GITHUB_SHA | head -c7}
